// Auto-generated by: supabase gen types typescript --local > src/lib/types/db.types.ts
// This stub exists for initial development. Run the command above after applying migrations.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          full_name: string | null
          avatar_url: string | null
          updated_at: string | null
        }
        Insert: {
          id: string
          full_name?: string | null
          avatar_url?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          full_name?: string | null
          avatar_url?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      businesses: {
        Row: {
          id: string
          owner_id: string
          name: string
          slug: string
          timezone: string
          description: string | null
          phone: string | null
          address: string | null
          logo_url: string | null
          is_active: boolean
          suspended_at: string | null
          plan: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          owner_id: string
          name: string
          slug: string
          timezone: string
          description?: string | null
          phone?: string | null
          address?: string | null
          logo_url?: string | null
          is_active?: boolean
          suspended_at?: string | null
          plan?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          owner_id?: string
          name?: string
          slug?: string
          timezone?: string
          description?: string | null
          phone?: string | null
          address?: string | null
          logo_url?: string | null
          is_active?: boolean
          suspended_at?: string | null
          plan?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'businesses_owner_id_fkey'
            columns: ['owner_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      business_members: {
        Row: {
          id: string
          business_id: string
          user_id: string
          role: 'owner' | 'manager' | 'staff'
          status: 'active' | 'invited' | 'removed'
          invited_at: string | null
          joined_at: string | null
        }
        Insert: {
          id?: string
          business_id: string
          user_id: string
          role: 'owner' | 'manager' | 'staff'
          status?: 'active' | 'invited' | 'removed'
          invited_at?: string | null
          joined_at?: string | null
        }
        Update: {
          id?: string
          business_id?: string
          user_id?: string
          role?: 'owner' | 'manager' | 'staff'
          status?: 'active' | 'invited' | 'removed'
          invited_at?: string | null
          joined_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'business_members_business_id_fkey'
            columns: ['business_id']
            isOneToOne: false
            referencedRelation: 'businesses'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'business_members_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      staff: {
        Row: {
          id: string
          business_id: string
          profile_user_id: string | null
          display_name: string
          email: string | null
          phone: string | null
          color_code: string
          bio: string | null
          avatar_url: string | null
          is_active: boolean
          archived_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          profile_user_id?: string | null
          display_name: string
          email?: string | null
          phone?: string | null
          color_code?: string
          bio?: string | null
          avatar_url?: string | null
          is_active?: boolean
          archived_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          profile_user_id?: string | null
          display_name?: string
          email?: string | null
          phone?: string | null
          color_code?: string
          bio?: string | null
          avatar_url?: string | null
          is_active?: boolean
          archived_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'staff_business_id_fkey'
            columns: ['business_id']
            isOneToOne: false
            referencedRelation: 'businesses'
            referencedColumns: ['id']
          }
        ]
      }
      services: {
        Row: {
          id: string
          business_id: string
          name: string
          description: string | null
          duration_minutes: number
          buffer_before_minutes: number
          buffer_after_minutes: number
          price: number | null
          is_active: boolean
          archived_at: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          name: string
          description?: string | null
          duration_minutes: number
          buffer_before_minutes?: number
          buffer_after_minutes?: number
          price?: number | null
          is_active?: boolean
          archived_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          name?: string
          description?: string | null
          duration_minutes?: number
          buffer_before_minutes?: number
          buffer_after_minutes?: number
          price?: number | null
          is_active?: boolean
          archived_at?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'services_business_id_fkey'
            columns: ['business_id']
            isOneToOne: false
            referencedRelation: 'businesses'
            referencedColumns: ['id']
          }
        ]
      }
      staff_services: {
        Row: {
          id: string
          business_id: string
          staff_id: string
          service_id: string
        }
        Insert: {
          id?: string
          business_id: string
          staff_id: string
          service_id: string
        }
        Update: {
          id?: string
          business_id?: string
          staff_id?: string
          service_id?: string
        }
        Relationships: [
          {
            foreignKeyName: 'staff_services_staff_id_fkey'
            columns: ['staff_id']
            isOneToOne: false
            referencedRelation: 'staff'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'staff_services_service_id_fkey'
            columns: ['service_id']
            isOneToOne: false
            referencedRelation: 'services'
            referencedColumns: ['id']
          }
        ]
      }
      business_hours: {
        Row: {
          id: string
          business_id: string
          weekday: number
          start_time: string
          end_time: string
          is_closed: boolean
        }
        Insert: {
          id?: string
          business_id: string
          weekday: number
          start_time: string
          end_time: string
          is_closed?: boolean
        }
        Update: {
          id?: string
          business_id?: string
          weekday?: number
          start_time?: string
          end_time?: string
          is_closed?: boolean
        }
        Relationships: [
          {
            foreignKeyName: 'business_hours_business_id_fkey'
            columns: ['business_id']
            isOneToOne: false
            referencedRelation: 'businesses'
            referencedColumns: ['id']
          }
        ]
      }
      staff_working_hours: {
        Row: {
          id: string
          business_id: string
          staff_id: string
          weekday: number
          start_time: string
          end_time: string
          is_off: boolean
        }
        Insert: {
          id?: string
          business_id: string
          staff_id: string
          weekday: number
          start_time: string
          end_time: string
          is_off?: boolean
        }
        Update: {
          id?: string
          business_id?: string
          staff_id?: string
          weekday?: number
          start_time?: string
          end_time?: string
          is_off?: boolean
        }
        Relationships: [
          {
            foreignKeyName: 'staff_working_hours_staff_id_fkey'
            columns: ['staff_id']
            isOneToOne: false
            referencedRelation: 'staff'
            referencedColumns: ['id']
          }
        ]
      }
      staff_time_off: {
        Row: {
          id: string
          business_id: string
          staff_id: string
          start_at: string
          end_at: string
          reason: string | null
          created_at: string
        }
        Insert: {
          id?: string
          business_id: string
          staff_id: string
          start_at: string
          end_at: string
          reason?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          staff_id?: string
          start_at?: string
          end_at?: string
          reason?: string | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'staff_time_off_staff_id_fkey'
            columns: ['staff_id']
            isOneToOne: false
            referencedRelation: 'staff'
            referencedColumns: ['id']
          }
        ]
      }
      customers: {
        Row: {
          id: string
          business_id: string
          full_name: string
          email: string | null
          phone: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          full_name: string
          email?: string | null
          phone?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          full_name?: string
          email?: string | null
          phone?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'customers_business_id_fkey'
            columns: ['business_id']
            isOneToOne: false
            referencedRelation: 'businesses'
            referencedColumns: ['id']
          }
        ]
      }
      bookings: {
        Row: {
          id: string
          business_id: string
          service_id: string
          staff_id: string
          customer_id: string
          status: 'pending' | 'confirmed' | 'cancelled' | 'completed' | 'no_show'
          start_at: string
          end_at: string
          effective_start_at: string
          effective_end_at: string
          timezone: string
          source: 'public' | 'admin'
          notes: string | null
          cancel_reason: string | null
          booking_access_token: string
          service_name_snapshot: string
          service_duration_minutes_snapshot: number
          buffer_before_snapshot: number
          buffer_after_snapshot: number
          price_snapshot: number | null
          staff_name_snapshot: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          service_id: string
          staff_id: string
          customer_id: string
          status?: 'pending' | 'confirmed' | 'cancelled' | 'completed' | 'no_show'
          start_at: string
          end_at: string
          effective_start_at: string
          effective_end_at: string
          timezone: string
          source?: 'public' | 'admin'
          notes?: string | null
          cancel_reason?: string | null
          booking_access_token?: string
          service_name_snapshot: string
          service_duration_minutes_snapshot: number
          buffer_before_snapshot?: number
          buffer_after_snapshot?: number
          price_snapshot?: number | null
          staff_name_snapshot?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          service_id?: string
          staff_id?: string
          customer_id?: string
          status?: 'pending' | 'confirmed' | 'cancelled' | 'completed' | 'no_show'
          start_at?: string
          end_at?: string
          effective_start_at?: string
          effective_end_at?: string
          timezone?: string
          source?: 'public' | 'admin'
          notes?: string | null
          cancel_reason?: string | null
          booking_access_token?: string
          service_name_snapshot?: string
          service_duration_minutes_snapshot?: number
          buffer_before_snapshot?: number
          buffer_after_snapshot?: number
          price_snapshot?: number | null
          staff_name_snapshot?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'bookings_business_id_fkey'
            columns: ['business_id']
            isOneToOne: false
            referencedRelation: 'businesses'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'bookings_staff_id_fkey'
            columns: ['staff_id']
            isOneToOne: false
            referencedRelation: 'staff'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'bookings_service_id_fkey'
            columns: ['service_id']
            isOneToOne: false
            referencedRelation: 'services'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'bookings_customer_id_fkey'
            columns: ['customer_id']
            isOneToOne: false
            referencedRelation: 'customers'
            referencedColumns: ['id']
          }
        ]
      }
      booking_audit_logs: {
        Row: {
          id: string
          booking_id: string
          action: string
          actor_type: string
          actor_id: string | null
          payload: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          booking_id: string
          action: string
          actor_type: string
          actor_id?: string | null
          payload?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          booking_id?: string
          action?: string
          actor_type?: string
          actor_id?: string | null
          payload?: Json | null
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'booking_audit_logs_booking_id_fkey'
            columns: ['booking_id']
            isOneToOne: false
            referencedRelation: 'bookings'
            referencedColumns: ['id']
          }
        ]
      }
      notification_logs: {
        Row: {
          id: string
          business_id: string
          booking_id: string | null
          type: string
          channel: string
          sent_to: string | null
          status: 'pending' | 'sent' | 'failed'
          created_at: string
        }
        Insert: {
          id?: string
          business_id: string
          booking_id?: string | null
          type: string
          channel?: string
          sent_to?: string | null
          status?: 'pending' | 'sent' | 'failed'
          created_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          booking_id?: string | null
          type?: string
          channel?: string
          sent_to?: string | null
          status?: 'pending' | 'sent' | 'failed'
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'notification_logs_business_id_fkey'
            columns: ['business_id']
            isOneToOne: false
            referencedRelation: 'businesses'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'notification_logs_booking_id_fkey'
            columns: ['booking_id']
            isOneToOne: false
            referencedRelation: 'bookings'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: Record<string, never>
    Functions: {
      create_booking: {
        Args: {
          p_business_id: string
          p_service_id: string
          p_staff_id: string
          p_customer_id: string
          p_start_at: string
          p_timezone: string
          p_source: string
          p_notes?: string | null
        }
        Returns: Database['public']['Tables']['bookings']['Row']
      }
      cancel_booking_by_token: {
        Args: { p_token: string; p_reason?: string | null }
        Returns: Database['public']['Tables']['bookings']['Row']
      }
      cancel_booking_by_member: {
        Args: { p_booking_id: string; p_reason?: string | null }
        Returns: Database['public']['Tables']['bookings']['Row']
      }
      reschedule_booking_by_token: {
        Args: { p_token: string; p_new_start_at: string }
        Returns: Database['public']['Tables']['bookings']['Row']
      }
      reschedule_booking_by_member: {
        Args: { p_booking_id: string; p_new_start_at: string }
        Returns: Database['public']['Tables']['bookings']['Row']
      }
    }
    Enums: Record<string, never>
  }
}
